Bloom Filter Sync Benchmarking
nislab/gensync-benchmarking pull request #1
Opened 2024-04-29 05:11 UTC by Anish701

2024-05-20 17:18 UTC, Chenxy517 approved these changes

2024-07-18 21:54 UTC, trachten requested changes

2024-07-18 21:54 UTC, trachten commented on example/example_params_dir/client_bf_0_0.cpisync
Why is this binary included in the pull request?

2024-07-18 21:54 UTC, trachten commented on example/example_params_dir/server_bf_0_0.cpisync
Why is this binary included in the pull request?

2024-07-18 22:24 UTC, Anish701 commented on example/example_params_dir/client_bf_0_0.cpisync
I chose to include the binary in the PR to provide users with an example for how the input file for the BFSync should be formatted. It is pretty similar to the CPISync inputs but with subtle differences (required false positive probability). Furthermore, the other binary input files will not work with BFSync, so I figured it might be beneficial to include a client and server binary input file which is specifically for the BFSync.

2024-07-18 22:25 UTC, Anish701 commented on example/example_params_dir/server_bf_0_0.cpisync
See reply above

2024-07-31 18:49 UTC, trachten commented on example/example_params_dir/client_bf_0_0.cpisync
It's not clear to me what this is the binary of ... is there some text in some README?

2024-08-02 16:10 UTC, Anish701 commented on example/example_params_dir/client_bf_0_0.cpisync
I deleted these example set reconciliation files as I included the parameter inputs for BFSync in the README. These files were similar to the existing ones present in the same directory(example datasets for reconciliation), with the only difference being that they used BFSync parameters rather than CPISync/CuckooSync parameters. However, since the BFSync parameter inputs are now shown in the README, there is no purpose in having these example files which are specific to BFSync.

2024-08-14 15:07 UTC, trachten approved these changes
Looks ok.

2024-08-14 15:07 UTC, merged